import Head from "next/head";
import * as React from "react";
import { Projects, ProjectType } from "../components/Projects";

import styles from "../styles/Home.module.css";

const Home = ({ projects }: ProjectType) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {projects ? <Projects projects={projects} /> : "loading"}
    </div>
  );
};

export default Home;
interface MappedProject {
  label: string;
  name?: string;
  id: string;
  rootFolderId: string;
}

export async function getServerSideProps() {
  const result = (await fetch("http://10.25.38.36:9090/").then((r) =>
    r.json()
  )) as ProjectType["projects"];

  const projects = result.map(
    ({ name: label, id, rootFolderId }: MappedProject) => {
      return {
        label,
        id,
        rootFolderId,
      };
    }
  ) as MappedProject[];

  return { props: { projects } };
}
