import Head from "next/head";
import * as React from "react";

import styles from "../styles/Home.module.css";
import { Button } from "../components/btn/Button";

const Home = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Report</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div
        style={{
          display: "flex",
          marginTop: "2rem",
          justifyContent: "center",
        }}
      >
        <div style={{ padding: "0 1rem" }}>
          <Button
            style={{
              backgroundColor: "#14213d",
            }}
            href={"/projects"}
          >
            Cost Report
          </Button>
        </div>
        <div>
          <Button
            style={{
              backgroundColor: "#fca311",
            }}
            href={"/bulidingtype"}
          >
            Building Type Cost
          </Button>
        </div>
      </div>
    </>
  );
};

export default Home;
